### ISSUE TITLE
Video running time feedback/variable

### ISSUE THREAD

**Issue by bscav** [leonreucher/powerpoint-remote-websocket#1]
Hi! 
This is a feature request. Maybe it would be possible for the plugin to read the current time and total time of videos playing inside powerpoint and send those values to companion. If possible this would be awesome.

Another idea is extracting notes info and sending them somewhere so let's say vmix can read them.

Thanks for your work!

**Comment by leonreucher** [comment]
Hey there,

I don't think that it's possible to get information about any clips running in an active presentation. 

I'll have a look into getting the current slides notes.

**Comment by leonreucher** [comment]
Added the notes part :)
