### ISSUE TITLE
windows 10 office 365 can't install it...

### ISSUE THREAD

**Issue by Valemax1981** [leonreucher/powerpoint-remote-websocket#2]
Hi there, i can't install it...this is the error while installing
System.Deployment.Application.InvalidDeploymentException: Aree di protezione non corrispondenti per la distribuzione e l'applicazione.
   in Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   in Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by leonreucher** [comment]
Please try it again with the latest release.

**Comment by troschak** [comment]
Hi
same problem on windows 11
![Screenshot 2023-12-02 125932](https://github.com/leonreucher/powerpoint-remote-websocket/assets/118544251/5916e3dc-d30f-4b54-a7c2-b9dcc433f699)

**Comment by leonreucher** [comment]
Could you please try to download the latest release with Internet Explorer/Edge?

**Comment by Valemax1981** [comment]
I will as soon as possbile :)

Il giorno sab 2 dic 2023 alle 12:08 leonreucher ***@***.***>
ha scritto:

**Comment by troschak** [comment]
i try latest release

**Comment by leonreucher** [comment]
And please make sure to run the installation.bat script, not the installer itself.

**Comment by troschak** [comment]
![Screenshot 2023-12-02 131206](https://github.com/leonreucher/powerpoint-remote-websocket/assets/118544251/fa2bec1b-388f-4a2c-ba8c-bd39a2091738)

**Comment by PittmanC** [comment]
Same issue. I also tried "Run as Admin".
![Screenshot 2024-01-08 084132](https://github.com/leonreucher/powerpoint-remote-websocket/assets/86573813/c53b1579-1aa0-475e-beee-bca4c8e093c9)

Win10
Office365

**Comment by chanx** [comment]
same with me, windows 11 23h2 and office 365? any update on this issue?

**Comment by JoZee01** [comment]
Same problem here

**Comment by kovike88** [comment]
Same problem here with fresh Win11 installation. :(

**Comment by leonreucher** [comment]
Okay, the solution is pretty easy. After downloading the ZIP file from the releases tab, right click the archive and show the properties. In this window check the "unblock" box.
![Bildschirmfoto 2024-02-20 um 16 10 32](https://github.com/leonreucher/powerpoint-remote-websocket/assets/19686873/9be59c4d-de4f-4642-aa6f-9ef70ffec504)
