### ISSUE TITLE
Connecting to the WebSocket and sending commands through the terminal.

### ISSUE THREAD

**Issue by Istavro** [leonreucher/powerpoint-remote-websocket#3]
Hello,

Don't have much experience working with web sockets, could  you provide a simple explanation of how I can send commands to the powerpoint websocket?

I want to do this in order to have an input device on the network send next and previous commands directly to powerpoint.

Edit: I am trying to use wscat but it is not connecting successfully.

Thank you!

**Comment by leonreucher** [comment]
Probably have a look around here for testing the websocket connection using an application like postman. 

https://learning.postman.com/docs/sending-requests/websocket/websocket-overview/

Just navigate through the pages and you will get a feeling about how WebSocket connections are working.

**Comment by Istavro** [comment]
I looked at the documentation you sent and I keep getting an error "501 Not implemented" Would you happen to know why that is?

Steps I took:
Install Postman Desktop
File -> New -> Websocket
Entered ws://ipaddr:80 
in the message I typed 
{
  "action": "next"
}

Please keep in mind that when I send an action through companion it works flawlessly.

Thank you again for all the help!

**Comment by meitzner-hannes** [comment]
There is a little problem with your sample:
The Address should be "ws://ipaddr:80/ws" like "ws://192.168.2.28:80/ws"

I was able to use Postman together with that add-in

> I looked at the documentation you sent and I keep getting an error "501 Not implemented" Would you happen to know why that is?
> 
> Steps I took: Install Postman Desktop File -> New -> Websocket Entered ws://ipaddr:80 in the message I typed { "action": "next" }
> 
> Please keep in mind that when I send an action through companion it works flawlessly.
> 
> Thank you again for all the help!

**Comment by Istavro** [comment]
Thank you that solved the issue!

Unfortunately I already implemented another solution using AHK.
