### ISSUE TITLE
Set open Presentation active instead of open a readonly copy

### ISSUE THREAD

**Issue by meitzner-hannes** [leonreucher/powerpoint-remote-websocket#4]
Hi! first of all, have many thanks for that addin! I have searched for something like that for a long time.
I tried it myself but I'm no programmer with experience with MS Stuff.

Now to the "problem":

When you use your add-in to open a presentation and doing it again  and again, you open several read-only copies of that presentation.

Would it be possible not to open a copy presentation but to only set it active?
I know that I could use the "CloseAllOther" Parameter, but, there are two reasons.

One workflow could be to just open several presentations just to load them and have the loading done beforehand.
So you can load all presentations in a break and just set the one active and start it when its needs to be live.

Two other things comes to mind in those scenarios: Exit and Load Presentations in the Background but that would be features of their own.

Here are the usecases:

OpenPresentation:
Check if a Presentation with the same path is open.
If its open, set it active
If its not open, open the presentation

**Comment by leonreucher** [comment]
Added in latest release - thank you for the input!
